### PR TITLE
End of user study

### PR DESCRIPTION
**Pull request by gallorob**
Removed user study mode from the application, updated codebase and build script.

@martinpoliak-goodai please double check that the application builds as intended: run `python build_main_webapp.py`, the executable will be created in the `dist` folder at the same level as the script. Launching the application should start it in user mode (no automatic population initialisation for now).

Merge the pull request if there are no issues, then I will continue updating the application--though this would be a release already.

### CODE REVIEW

**Comment by martinpoliak-goodai** [comment]
Got a build warning 'Unable to find "space-engineers-ai-spaceship-generator\block_definitions.json" when adding binary and data files.' The executable was not built; it is possible that the file is missing from git?

**Comment by gallorob** [comment]
Ah sorry, guess it was on the `.gitignore`. I've added it back now.

**Comment by martinpoliak-goodai** [comment]
I'm testing the app; after the latest update, the build launches an app that shows no population - is this intentional? I would prefer if an initial population was loaded into the the UI and some ship was selected, to avoid the black visualization windows.

________________________________

**Comment by martinpoliak-goodai** [comment]
Not sure if related - I reset the population, chose a spaceship and hit evolve from selected (in Chrome). Afterwards I got the following error in the log and the app stop responding. Will now try with debug flag on.

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
  File "pcgsepy\guis\main_webapp\webapp.py", line 2925, in general_callback
  File "pcgsepy\guis\main_webapp\webapp.py", line 1888, in __apply_step
KeyError: 'eoe_modal_show'
[2022-12-12 09:26:51,221] Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
  File "pcgsepy\guis\main_webapp\webapp.py", line 2925, in general_callback
  File "pcgsepy\guis\main_webapp\webapp.py", line 1888, in __apply_step
KeyError: 'eoe_modal_show'


________________________________

**Comment by gallorob** [comment]
Yes, no initial population is intentional. I can change it to generate one on-launch, though it will take roughly the same amount of time as reinitializing one.

As for the error, I will double check, it seems I missed a line when refactoring.

**Comment by martinpoliak-goodai** [comment]
Hi Roberto,

I replicated the error below again with debug flag on, logs are attached.


There are two more UI bits that may be related - after I refresh the browser window using F5, the ship preview screen is blank until I choose a different ship bin. Also the "safe mode" toggle jumps back to safe even though I initially set it to False before refreshing the UI; logs show no switching back to True.


Cheers,

Martin

________________________________

**Comment by martinpoliak-goodai** [comment]
Yes please, I prefer to see a spaceship and an initial population after the app loads, despite having to wait for a bit until everything is ready.

________________________________

**Comment by gallorob** [comment]
@martinpoliak-goodai I fixed the mentioned issues--reloading also maintains user selections and currently displayed spaceship. 

Just one thing I want to confirm: 

> I prefer to see a spaceship and an initial population after the app loads

this was not the default behaviour of the user mode. In the original user mode, no spaceship is selected by default upon population initialisation. Do you want me to change it so that it selects automatically a spaceship (I guess randomly)?

**Comment by martinpoliak-goodai** [comment]
"Do you want me to change it so that it selects automatically a spaceship (I guess randomly)?"

Yes please, I think it helps a lot. It is not obvious from UI perspective that the first thing to do after the application loads is to click the Initialize Population button. (just a note: while the user study was running, most people would start with the user study mode and thus get used to the UI - that is no longer possible now.)

________________________________

**Comment by gallorob** [comment]
@martinpoliak-goodai I've changed the init behaviour, now it generates a new population on startup and automatically selects one of the valid cells, displaying the spaceship within.

Please check if the behaviour is as described and is what you had in mind, and let me know if there are any issues 😃

**Comment by martinpoliak-goodai** [comment]
Clicking download triggers a download animation and also the following error in the log:

[2022-12-12 15:34:45]    [pcgsepy.guis.main_webapp.webapp.general_callback] Unrecognized event_trig='download-btn'. No operations have been applied!

________________________________

**Comment by martinpoliak-goodai** [comment]
We'll get to the release, but not yet :-D


The newest build throws the following error right after I launch the application and the browser window opens:


Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
TypeError: general_callback() missing 1 required positional argument: 'confirm_unsafemode_switch'
[2022-12-12 15:52:08,410] Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
TypeError: general_callback() missing 1 required positional argument: 'confirm_unsafemode_switch'


The application does not load afterwards, buttons do not have any effect and no population is displayed.

________________________________

**Comment by gallorob** [comment]
Fixed, my bad!

**Comment by martinpoliak-goodai** [comment]
I tested spaceship generation, download, loading into game and it all works fine!
obrazek

**Review by martinpoliak-goodai — APPROVED** [review]
For details, please refer to the discussion above. The build was tested and works fine. I'll merge now.

**Pull request merged**
